# caffeine-concurrency-bug

Causing Concurrent exception while using lot of threads:

```shell
java.sql.SQLException: The database has been closed
	at org.sqlite.core.NativeDB.throwex(NativeDB.java:478)
	at org.sqlite.core.NativeDB.column_blob(Native Method)
	at org.sqlite.jdbc3.JDBC3ResultSet.getBytes(JDBC3ResultSet.java:260)
	at org.sqlite.jdbc3.JDBC3ResultSet.getBytes(JDBC3ResultSet.java:267)
	at cafconc.SQLiteManager.get(SQLiteManager.java:53)
	at cafconc.CaffeineConcurrency.getValue(CaffeineConcurrency.java:23)
	at cafconc.CaffeineConcurrency.lambda$main$2(CaffeineConcurrency.java:35)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
java.sql.SQLException: The database has been closed
	at org.sqlite.core.NativeDB.throwex(NativeDB.java:478)
	at org.sqlite.core.NativeDB.column_blob(Native Method)
	at org.sqlite.jdbc3.JDBC3ResultSet.getBytes(JDBC3ResultSet.java:260)
	at org.sqlite.jdbc3.JDBC3ResultSet.getBytes(JDBC3ResultSet.java:267)
	at cafconc.SQLiteManager.get(SQLiteManager.java:53)
	at cafconc.CaffeineConcurrency.getValue(CaffeineConcurrency.java:23)
	at cafconc.CaffeineConcurrency.lambda$main$2(CaffeineConcurrency.java:35)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
java.sql.SQLException: The database has been closed
	at org.sqlite.core.NativeDB.throwex(NativeDB.java:478)
	at org.sqlite.core.NativeDB.column_blob(Native Method)
	at org.sqlite.jdbc3.JDBC3ResultSet.getBytes(JDBC3ResultSet.java:260)
	at org.sqlite.jdbc3.JDBC3ResultSet.getBytes(JDBC3ResultSet.java:267)
	at cafconc.SQLiteManager.get(SQLiteManager.java:53)
	at cafconc.CaffeineConcurrency.getValue(CaffeineConcurrency.java:23)
	at cafconc.CaffeineConcurrency.lambda$main$2(CaffeineConcurrency.java:35)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
java.sql.SQLException: The database has been closed
	at org.sqlite.core.NativeDB.throwex(NativeDB.java:478)
	at org.sqlite.core.NativeDB.column_blob(Native Method)
	at org.sqlite.jdbc3.JDBC3ResultSet.getBytes(JDBC3ResultSet.java:260)
	at org.sqlite.jdbc3.JDBC3ResultSet.getBytes(JDBC3ResultSet.java:267)
	at cafconc.SQLiteManager.get(SQLiteManager.java:53)
	at cafconc.CaffeineConcurrency.getValue(CaffeineConcurrency.java:23)
	at cafconc.CaffeineConcurrency.lambda$main$2(CaffeineConcurrency.java:35)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
java.sql.SQLException: statement is not executing
	at org.sqlite.core.CoreStatement.checkOpen(CoreStatement.java:55)
	at org.sqlite.jdbc3.JDBC3Statement.getResultSet(JDBC3Statement.java:126)
	at org.sqlite.jdbc3.JDBC3Statement.executeQuery(JDBC3Statement.java:80)
	at cafconc.SQLiteManager.get(SQLiteManager.java:48)
	at cafconc.CaffeineConcurrency.getValue(CaffeineConcurrency.java:23)
	at cafconc.CaffeineConcurrency.lambda$main$2(CaffeineConcurrency.java:35)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
java.sql.SQLException: The prepared statement has been finalized
	at org.sqlite.core.NativeDB.throwex(NativeDB.java:478)
	at org.sqlite.core.NativeDB.column_count(Native Method)
	at org.sqlite.core.DB.column_names(DB.java:722)
	at org.sqlite.jdbc3.JDBC3Statement.getResultSet(JDBC3Statement.java:138)
	at org.sqlite.jdbc3.JDBC3Statement.executeQuery(JDBC3Statement.java:80)
	at cafconc.SQLiteManager.get(SQLiteManager.java:48)
	at cafconc.CaffeineConcurrency.getValue(CaffeineConcurrency.java:23)
	at cafconc.CaffeineConcurrency.lambda$main$2(CaffeineConcurrency.java:35)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
  ```
